### ISSUE TITLE
Translations not working

### ISSUE THREAD

**Issue by SCjoh** [4tronix/BitBot#5]
Suddenly, after the summer updates, the norwegian translations stopped working. Any idea why?

**Comment by SCjoh** [comment]
Here are attached translation files with the new blocks. Perhaps try if this works?


[locales_folder.zip](https://github.com/4tronix/BitBot/files/3520490/locales_folder.zip)

**Comment by SCjoh** [comment]
After some testing, I think the issue is that the name of the extention changed from bitbot to BitBot, and the _locales files have to reflect that change. The include section in the pxt.json file also need to be changed to BitBot. I have attached _locales files with the right file names, and translations for the new blocks. Please replace the _locales files and update pxt.json to reflect the new file names. Thank you.
[_locales.zip](https://github.com/4tronix/BitBot/files/3520693/_locales.zip)

**Comment by 4tronix** [comment]
Files updated as requested. Cheers!
