### ISSUE TITLE
BitBot extension not loading in makecode

### ISSUE THREAD

**Issue by SCjoh** [4tronix/BitBot#6]
Thanks for the quick updates, and sorry for the hassle. Right now, the BitBot extension gives the error message "network request failed" due to the name change from bitbot to BitBot. 

The pxt.json file refers to 
        "_locales/no/BitBot-strings.json",
        "_locales/no/BitBot-jsdoc-strings.json"

However, the files themselves are still all in lowercase, causing the "network request failed" error message. So the file names in the _locales folder needs the uppercase B's.

**Comment by 4tronix** [comment]
yes - I'm working on it now. I suspect it was because I made the change on a Windows PC. All the local files have the correct upper case names, but that didn't translate when pushed to Github. Should be okay in a few minutes...

**Comment by 4tronix** [comment]
It is fixed now. Please confirm

**Comment by SCjoh** [comment]
Works like a charm. Thanks again for the quick response!

**Comment by 4tronix** [comment]
thanks for confirming
