### ISSUE TITLE
Goes into pair mode unexpectedly when using the radio

### ISSUE THREAD

**Issue by Geoffree3** [4tronix/BitBot#7]
I was having a problem with the Bit:Bot (v.1.1) going into pair mode when it received/sent a radio message.  Then it happened when the micro:bit usb lead was unplugged from the computer. Although the micro:bit was still working (i.e. not dead batteries) I replaced the batteries and this seems to have fixed the issue. Perhaps a problem with the voltage regulator that is enough to cause a reset?

**Comment by 4tronix** [comment]
Sorry. Missed this.
The only conclusion I can draw is that low power in the batteries will cause a reset when power is drained for motors and/or radio usage. In later models the fuse on the battery pack has been removed which allows for longer use on flatter batteries. You could try replacing the fuse with a short circuit. Anyway, this isn't a software issue, so I will close the issue.
Thanks,
Gareth
