### ISSUE TITLE
Renaming main.ts to bitbot.ts has broke the extension in MakeCode

### ISSUE THREAD

**Issue by stevenp1986** [4tronix/BitBot#9]
Hi,

Tried adding extension in makecode but comes back with a 404 as it's looking for main.ts

forked the repository and renamed bitbot.ts back to main.ts and I was able to add it back in.
<img width="548" alt="bitbot 404" src="https://user-images.githubusercontent.com/60850575/74105714-349b0000-4b58-11ea-9c14-8a7fd2050bad.png">

Thanks

Steven

**Comment by 4tronix** [comment]
Hi,
Thanks for letting me know. That was a change in preparation for an 
update coming soon.
Makecode should not have picked that up as it isn't in a Release and it 
should only pick up files from a Release
Anyway, the necessary change to pxt.json has now also been made.

I just tried loading it and it didn't work. Then tried again 5 minutes 
later and now it is working - but it is doing what it should do - load 
the release files, not the new files

Thanks again,
Gareth

------ Original Message ------

**Comment by 4tronix** [comment]
And this is what is een in the file explorer in Makecode as of this 
minute

Gareth

------ Original Message ------
From: "4tronix" <sales@4tronix.co.uk>
To: "4tronix/BitBot" 
<reply@reply.github.com>
Sent: 09/02/2020 16:42:10
Subject: Re: [4tronix/BitBot] Renaming main.ts to bitbot.ts has broke 
the extension in MakeCode (#9)

**Comment by stevenp1986** [comment]
Hi Gareth,

Thanks for the update and the quick response.

Just tried again and it's now working.

Kind Regards

Steven

**Comment by 4tronix** [comment]
Hi,
Yes. It turns out that it was one of the Makecode/GitHub search glitches that happen surprisingly often

Best regards,
Gareth
